- id: statelint
  name: statelint
  entry: statelint
  language: python
  types: [json]
  require_serial: true
- id: statelint-yaml
  name: statelint (YAML)
  entry: statelint --yaml
  language: python
  types: [yaml]
  require_serial: true
