name: pytest
on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: 3.6
            lint: false
          - os: ubuntu-latest
            python: 3.9
            lint: true
          - os: windows-latest
            python: 3.6
            lint: false
          - os: windows-latest
            python: 3.9
            lint: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/test.txt

      - name: Lint
        if: ${{ matrix.lint }}
        uses: pre-commit/action@v2.0.3

      - name: Run test suite
        run: |
          pytest tests
