name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: 3.9
            type: test-only
          - os: ubuntu-latest
            python: 3.13
            type: all
          - os: windows-latest
            python: 3.13
            type: test-only
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/test.txt

      - name: Lint
        if: matrix.type == 'all'
        uses: pre-commit/action@v3.0.1

      - name: Run test suite
        if: matrix.type != 'all'
        run: pytest tests

      - name: Coveralls
        if: matrix.type == 'all'
        run: |
          pip install coveralls
          coverage run --source=statelint -m pytest tests
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
