name: Test
on:
  pull_request:
  push:

jobs:
  test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: 3.8
            type: test-only
          - os: ubuntu-latest
            python: 3.11
            type: all
          - os: windows-latest
            python: 3.11
            type: test-only
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/test.txt

      - name: Lint
        if: ${{ matrix.type == 'all' }}
        uses: pre-commit/action@v3.0.1

      - name: Run test suite
        if: ${{ matrix.type != 'all' }}
        run: |
          pytest tests

      - name: Coveralls
        if: ${{ matrix.type == 'all' }}
        run: |
          pip install coveralls
          coverage run --source=statelint -m pytest tests
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
