name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: 3.9
            type: test-only
          - os: ubuntu-latest
            python: 3.13
            type: all
          - os: windows-latest
            python: 3.13
            type: test-only
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/test.txt

      - name: Lint
        if: matrix.type == 'all'
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

      - name: Run test suite
        if: matrix.type != 'all'
        run: pytest tests

      - name: Run test suite with coverage
        if: matrix.type == 'all'
        run: coverage run --source=statelint -m pytest tests

      - name: Coveralls
        if: matrix.type == 'all'
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
        with:
          format: python
